### ISSUE TITLE
repetitive information

### ISSUE THREAD

**Issue by maklh899** [introdsci/DataScience-rtresendez#4]
Because you have a column for states, I think it would be best to take out the state acronym in the county column
https://github.com/introdsci/DataScience-rtresendez/blob/71a6cbce3f88b10c8e54f71bc5fe627ee210cd90/Portfolio.Rmd#L237

**Comment by rtresendez** [comment]
Due to the way the Data is set up this will need to stay as is. If I removed this column then the data would not make sense as the numerical values are categorical based on the State its from.
