### ISSUE TITLE
p02 Peer Review Summary

### ISSUE THREAD

**Issue by capktkirk** [introdsci/DataScience-rtresendez#8]
Data Preparation - The data is well prepared, and it is easy to view through. The renaming of the columns and rearranging of them into tidy data is done well.

    Modeling - The plots demonstrate good information, and show the information that is going to be modeled for the future of labor.

    R proficiency - The code is well prepared and fluent. A furthering use of aesthetic manipulation might be nice just to differentiate the plots.

    Communication - It is clear what Reese is attempting to map out and compare, I would consider renaming the CIP2_ID/CIP4_ID, CIP6_ID into something that is human readable. That would be a difficult thing though, as it is a complex concept. I think it is acceptable to keep them in their cryptic form with the descriptions on line 80 through line 85.

    Critical thinking - The concepts behind this comparison is valid, and is interesting. I would be interested in seeing a third dataset maybe with correlation on violence or crime statistics in comparison with areas having a high secondary education rate.

    Feedback - I mention the third dataset in critical thinking, but I don't have any real feedback. Everything is good, and I put any feedback in the specific areas concerning the specific feedback.

**Comment by rtresendez** [comment]
Notes taken! I will look into implementing a third dataset,
